port: 8000
metricsPort: 9092
nats: nats://localhost:4222
redis:
  dsn: redis://localhost:6379
s3:
  endpoint: "localhost:9000"
  accessKeyID: "minio"
  secretAccessKey: "minio123"
  buckets:
    - texts
elastic:
  hosts:
    - http://localhost:9200/
  startupIndex:
    - index: "shingle_index"
      updateMapping: true
      createMapping: true
      mappingPath: "config/mappings/shingle_index.json"
      alias: ""
      shards: 1
      replics: 1
shingleRepo:
  index: "shingle_index"
