port: 8000
metricsPort: 9092
nats: nats://localhost:4222
redis:
  dsn: redis://localhost:6379
s3:
  endpoint: "localhost:9000"
  accessKeyID: "minio"
  secretAccessKey: "minio123"
  buckets:
    - texts
