// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v4.25.0
// source: proto/similarityindex.proto

package similarityindex

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchSimilarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSimilarRequest) Reset() {
	*x = SearchSimilarRequest{}
	mi := &file_proto_similarityindex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSimilarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSimilarRequest) ProtoMessage() {}

func (x *SearchSimilarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_similarityindex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSimilarRequest.ProtoReflect.Descriptor instead.
func (*SearchSimilarRequest) Descriptor() ([]byte, []int) {
	return file_proto_similarityindex_proto_rawDescGZIP(), []int{0}
}

func (x *SearchSimilarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SearchSimilarResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Error         *Error                     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Matches       []*SimilarityDocumentMatch `protobuf:"bytes,2,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSimilarResponse) Reset() {
	*x = SearchSimilarResponse{}
	mi := &file_proto_similarityindex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSimilarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSimilarResponse) ProtoMessage() {}

func (x *SearchSimilarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_similarityindex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSimilarResponse.ProtoReflect.Descriptor instead.
func (*SearchSimilarResponse) Descriptor() ([]byte, []int) {
	return file_proto_similarityindex_proto_rawDescGZIP(), []int{1}
}

func (x *SearchSimilarResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SearchSimilarResponse) GetMatches() []*SimilarityDocumentMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type SimilarityDocumentMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rate          float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Highlights    []string               `protobuf:"bytes,3,rep,name=highlights,proto3" json:"highlights,omitempty"`
	SimilarImages []string               `protobuf:"bytes,4,rep,name=similar_images,json=similarImages,proto3" json:"similar_images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimilarityDocumentMatch) Reset() {
	*x = SimilarityDocumentMatch{}
	mi := &file_proto_similarityindex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimilarityDocumentMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimilarityDocumentMatch) ProtoMessage() {}

func (x *SimilarityDocumentMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_similarityindex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimilarityDocumentMatch.ProtoReflect.Descriptor instead.
func (*SimilarityDocumentMatch) Descriptor() ([]byte, []int) {
	return file_proto_similarityindex_proto_rawDescGZIP(), []int{2}
}

func (x *SimilarityDocumentMatch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SimilarityDocumentMatch) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *SimilarityDocumentMatch) GetHighlights() []string {
	if x != nil {
		return x.Highlights
	}
	return nil
}

func (x *SimilarityDocumentMatch) GetSimilarImages() []string {
	if x != nil {
		return x.SimilarImages
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_similarityindex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_similarityindex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_similarityindex_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Error) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_similarityindex_proto protoreflect.FileDescriptor

var file_proto_similarityindex_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69,
	0x74, 0x79, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73,
	0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x26,
	0x0a, 0x14, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x89, 0x01, 0x0a, 0x15, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x42,
	0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x28, 0x2e, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x2e, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x73, 0x22, 0x84, 0x01, 0x0a, 0x17, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74,
	0x79, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x72, 0x61,
	0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x69, 0x67, 0x68, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x69, 0x67, 0x68, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x5f, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x69, 0x6d, 0x69,
	0x6c, 0x61, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x22, 0x41, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x71, 0x0a, 0x0f,
	0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x5e, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72,
	0x12, 0x25, 0x2e, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61,
	0x72, 0x69, 0x74, 0x79, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x1b, 0x5a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x69, 0x6d,
	0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_similarityindex_proto_rawDescOnce sync.Once
	file_proto_similarityindex_proto_rawDescData []byte
)

func file_proto_similarityindex_proto_rawDescGZIP() []byte {
	file_proto_similarityindex_proto_rawDescOnce.Do(func() {
		file_proto_similarityindex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_similarityindex_proto_rawDesc), len(file_proto_similarityindex_proto_rawDesc)))
	})
	return file_proto_similarityindex_proto_rawDescData
}

var file_proto_similarityindex_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_similarityindex_proto_goTypes = []any{
	(*SearchSimilarRequest)(nil),    // 0: similarityindex.SearchSimilarRequest
	(*SearchSimilarResponse)(nil),   // 1: similarityindex.SearchSimilarResponse
	(*SimilarityDocumentMatch)(nil), // 2: similarityindex.SimilarityDocumentMatch
	(*Error)(nil),                   // 3: similarityindex.Error
}
var file_proto_similarityindex_proto_depIdxs = []int32{
	3, // 0: similarityindex.SearchSimilarResponse.error:type_name -> similarityindex.Error
	2, // 1: similarityindex.SearchSimilarResponse.matches:type_name -> similarityindex.SimilarityDocumentMatch
	0, // 2: similarityindex.SimilarityIndex.SearchSimilar:input_type -> similarityindex.SearchSimilarRequest
	1, // 3: similarityindex.SimilarityIndex.SearchSimilar:output_type -> similarityindex.SearchSimilarResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_similarityindex_proto_init() }
func file_proto_similarityindex_proto_init() {
	if File_proto_similarityindex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_similarityindex_proto_rawDesc), len(file_proto_similarityindex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_similarityindex_proto_goTypes,
		DependencyIndexes: file_proto_similarityindex_proto_depIdxs,
		MessageInfos:      file_proto_similarityindex_proto_msgTypes,
	}.Build()
	File_proto_similarityindex_proto = out.File
	file_proto_similarityindex_proto_goTypes = nil
	file_proto_similarityindex_proto_depIdxs = nil
}
