port: ${PORT}

metricsPort: ${METRICS_PORT}

s3:
  endpoint: "${S3_ENDPOINT}"
  accessKeyID: "${S3_ACCESS_KEY}"
  secletAccessKey: "${S3_SECRET_KEY}"
  buckets:
    - ${S3_BUCKET_IMAGES}
    - ${S3_BUCKET_TEXTS}
    - ${S3_BUCKET_ANYSAVE}

elastic:
  hosts:
    - ${ELASTIC_HOSTS}
  startupIndex:
    - index: ${ELASTIC_DOCUMENT_INDEX}
      updateMapping: ${ELASTIC_UPDATE_MAPPING_ELASTIC_DOCUMENT_INDEX}
      createMapping: ${ELASTIC_CREATE_MAPPING_ELASTIC_DOCUMENT_INDEX}
      mappingPath: ${ELASTIC_MAPPING_PATH_ELASTIC_DOCUMENT_INDEX}
      alias: ${ELASTIC_ALIAS_ELASTIC_DOCUMENT_INDEX}
      shards: ${ELASTIC_SHARDS_ELASTIC_DOCUMENT_INDEX}
      replics: ${ELASTIC_REPLICAS_ELASTIC_DOCUMENT_INDEX}

nats: ${NATS_URL}

tika: ${TIKA_URL}

attributeRepo:
  index: "${ATTRIBUTE_REPO_INDEX}"

documentRepo:
  index: "${DOCUMENT_REPO_INDEX}"
