metricsPort: ${METRICS_PORT}

s3:
  endpoint: "${S3_ENDPOINT}"
  accessKeyID: "${S3_ACCESS_KEY}"
  secretAccessKey: "${S3_SECRET_KEY}"
  buckets:
    - ${S3_BUCKET_TEXTS}

elastic:
  hosts:
    - ${ELASTIC_HOSTS}
  startupIndex:
    - index: "${ELASTIC_FULLTEXT_INDEX}"
      updateMapping: ${ELASTIC_UPDATE_MAPPING_ELASTIC_FULLTEXT_INDEX}
      createMapping: ${ELASTIC_CREATE_MAPPING_ELASTIC_FULLTEXT_INDEX}
      mappingPath: ${ELASTIC_MAPPING_PATH_ELASTIC_FULLTEXT_INDEX}
      alias: ${ELASTIC_ALIAS_ELASTIC_FULLTEXT_INDEX}
      shards: ${ELASTIC_SHARDS_ELASTIC_FULLTEXT_INDEX}
      replicas: ${ELASTIC_REPLICAS_ELASTIC_FULLTEXT_INDEX}

nats: ${NATS_URL}

fulltextRepo:
  index: "${FULLTEXT_REPO_INDEX}"
