port: ${PORT}

metricsPort: ${METRICS_PORT}

s3:
  endpoint: "${S3_ENDPOINT}"
  accessKeyID: "${S3_ACCESS_KEY}"
  secletAccessKey: "${S3_SECRET_KEY}"
  buckets:
    - ${S3_BUCKET_TEXTS}

elastic:
  hosts:
    - ${ELASTIC_HOSTS}
  indexopts:
    - index: "${ELASTIC_SIMILARITY_INDEX}"
      updateMapping: ${ELASTIC_UPDATE_MAPPING_SIMILARITY_INDEX}
      createMapping: ${ELASTIC_CREATE_MAPPING_SIMILARITY_INDEX}
      mappingPath: "${ELASTIC_MAPPING_PATH_SIMILARITY_INDEX}"
      alias: "${ELASTIC_ALIAS_SIMILARITY_INDEX}"
      shards: ${ELASTIC_SHARDS_SIMILARITY_INDEX}
      replics: ${ELASTIC_REPLICAS_SIMILARITY_INDEX}

nats: ${NATS_URL}

analyzeHistoryRepo:
  index: "${ANALYZE_HISTORY_REPO_INDEX}"
