apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: gateway
  hostnames:
    - "{{ include "app.fullname" . }}.{{ .Values.service.domain }}"
  rules:
    - backendRefs:
        - name: {{ include "app.fullname" . }}-service
          port: {{ .Values.service.port }}
