openapi: 3.0.0
info:
  title: Document Similarity API
  description: API для анализа сходства документов и поиска документов по имени
  version: 1.5.0

paths:
  /document/upload:
    post:
      summary: Загрузка документа
      description: Загружает документ для дальнейшего анализа на сходство.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/UploadRequest"
      responses:
        "200":
          $ref: "#/components/responses/UploadSuccess"
        "400":
          $ref: "#/components/responses/BadRequest"

  /document/{document_id}/download:
    get:
      summary: Скачать документ
      description: Позволяет скачать загруженный документ по его идентификатору.
      parameters:
        - $ref: "#/components/parameters/DocumentId"
      responses:
        "200":
          description: Успешная загрузка документа
          headers:
            Content-Disposition:
              schema:
                type: string
                example: attachment; filename="example.docx"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "404":
          $ref: "#/components/responses/DocumentNotFound"

  /documents/search:
    post:
      summary: Поиск документов по имени
      description: Получить список документов, соответствующих заданному имени.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchRequest"
      responses:
        "200":
          description: Успешный ответ с документами
          content:
            application/json:
              schema:
                type: object
                properties:
                  documents:
                    type: array
                    items:
                      $ref: "#/components/schemas/DocumentSummary"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/ServerError"

components:
  schemas:
    UploadRequest:
      type: object
      properties:
        document:
          type: string
          format: binary
          description: Документ для загрузки

    SearchRequest:
      type: object
      properties:
        name:
          type: string
          description: Имя документа для поиска
          example: "Документ 1"

    Document:
      type: object
      properties:
        ID:
          type: string
        ImageIDs:
          type: array
          items:
            type: string
        TextContent:
          type: string
          description: Содержимое текста документа

    DocumentSummary:
      type: object
      properties:
        id:
          type: string
          description: Идентификатор документа
          example: "123"
        name:
          type: string
          description: Имя документа
          example: "Документ 1"
        lastUpdated:
          type: string
          format: date-time
          description: Дата обновления документа
          example: "2024-10-01T12:00:00Z"

    CompareRequest:
      type: object
      properties:
        documentIDs:
          type: array
          items:
            type: string
          description: Список идентификаторов документов для сравнения

    ComparisonResult:
      type: object
      properties:
        similarity_score:
          type: number
          format: float
          description: Процент сходства между документами (от 0 до 100)
        details:
          type: array
          items:
            type: object
            properties:
              documentID:
                type: string
              otherDocumentID:
                type: string
              similarity:
                type: number
                format: float
                description: Процент сходства между парой документов

  responses:
    UploadSuccess:
      description: Документ успешно загружен
      content:
        application/json:
          schema:
            type: object
            properties:
              documentID:
                type: string
                description: Уникальный идентификатор загруженного документа

    ComparisonResult:
      description: Результаты сравнения документов
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ComparisonResult"

    DocumentNotFound:
      description: Документ не найден
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Документ не найден"

    BadRequest:
      description: Ошибка валидации или неверный формат запроса
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Неверный запрос"

    ServerError:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Ошибка сервера"

  parameters:
    DocumentId:
      name: document_id
      in: path
      required: true
      schema:
        type: string
      description: Уникальный идентификатор документа
