openapi: 3.0.0
info:
  title: Document Similarity API
  description: API для анализа сходства документов и поиска документов по имени
  version: 1.5.0

paths:
  /document/upload:
    post:
      summary: Загрузка документа
      description: Загружает документ для дальнейшего анализа на сходство.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/UploadRequest"
      responses:
        "200":
          $ref: "#/components/responses/UploadSuccess"
        "400":
          $ref: "#/components/responses/BadRequest"

  /document/{document_id}/download:
    get:
      summary: Скачать документ
      description: Позволяет скачать загруженный документ по его идентификатору.
      parameters:
        - $ref: "#/components/parameters/DocumentId"
      responses:
        "200":
          description: Успешная загрузка документа
          headers:
            Content-Disposition:
              schema:
                type: string
                example: attachment; filename="example.docx"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "404":
          $ref: "#/components/responses/DocumentNotFound"

  /document/search:
    post:
      summary: Поиск документов по имени
      description: Получить список документов, соответствующих заданному имени.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchRequest"
      responses:
        "200":
          $ref: "#/components/responses/SearchResult"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/ServerError"

  /analyze/{document_id}/similar:
    get:
      summary: Поиск подожих документов
      description: Получить список документов, наиболее похожих на загруженный
      parameters:
        - $ref: "#/components/parameters/DocumentId"
      responses:
        "200":
          $ref: "#/components/responses/SimilaritySearchResult"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/ServerError"

components:
  schemas:
    UploadRequest:
      type: object
      properties:
        document:
          type: string
          format: binary
          description: Документ для загрузки

    SearchRequest:
      type: object
      properties:
        name:
          type: string
          description: Имя документа для поиска
          example: "Документ 1"

    Document:
      type: object
      properties:
        ID:
          type: string
        ImageIDs:
          type: array
          items:
            type: string
        TextContent:
          type: string
          description: Содержимое текста документа

    DocumentSummary:
      type: object
      properties:
        id:
          type: string
          description: Идентификатор документа
          example: "123"
        name:
          type: string
          description: Имя документа
          example: "Документ 1"
        lastUpdated:
          type: string
          format: date-time
          description: Дата обновления документа
          example: "2024-10-01T12:00:00Z"

    AnalyzedDocumentMatch:
      type: object
      properties:
        id:
          type: string
          description: Уникальный идентификатор документа.
        rate:
          type: number
          format: float
          description: Коэффициент похожести (например, от 0 до 1).
        highlights:
          type: array
          items:
            type: string
          description: Список фрагментов текста, которые совпадают в документах.
        similarImages:
          type: array
          items:
            type: string
          description: Список идентификаторов похожих изображений.

  responses:
    UploadSuccess:
      description: Документ успешно загружен
      content:
        application/json:
          schema:
            type: object
            properties:
              documentID:
                type: string
                description: Уникальный идентификатор загруженного документа

    SearchResult:
      description: Результаты поиска документов
      content:
        application/json:
          schema:
            type: object
            properties:
              documents:
                type: array
                items:
                  $ref: "#/components/schemas/DocumentSummary"

    SimilaritySearchResult:
      description: Результаты поиска схожих документов
      content:
        application/json:
          schema:
            type: object
            properties:
              documents:
                type: array
                items:
                  $ref: "#/components/schemas/AnalyzedDocumentMatch"

    DocumentNotFound:
      description: Документ не найден
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Документ не найден"

    BadRequest:
      description: Ошибка валидации или неверный формат запроса
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Неверный запрос"

    ServerError:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Ошибка сервера"

  parameters:
    DocumentId:
      name: document_id
      in: path
      required: true
      schema:
        type: string
      description: Уникальный идентификатор документа
