// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"context"
	"github.com/elastic/go-elasticsearch/v8"
	"github.com/minio/minio-go/v7"
	"github.com/nats-io/nats.go"
	"github.com/zuzuka28/simreport/lib/elasticutil"
	"github.com/zuzuka28/simreport/lib/httpinstumentation"
	"github.com/zuzuka28/simreport/lib/minioutil"
	"github.com/zuzuka28/simreport/prj/fulltextindex/internal/config"
	server2 "github.com/zuzuka28/simreport/prj/fulltextindex/internal/handler/nats/event"
	"github.com/zuzuka28/simreport/prj/fulltextindex/internal/handler/nats/event/handler/indexer"
	fulltextindex3 "github.com/zuzuka28/simreport/prj/fulltextindex/internal/handler/nats/micro/handler/fulltextindex"
	"github.com/zuzuka28/simreport/prj/fulltextindex/internal/handler/nats/micro/server"
	"github.com/zuzuka28/simreport/prj/fulltextindex/internal/metrics"
	"github.com/zuzuka28/simreport/prj/fulltextindex/internal/model"
	"github.com/zuzuka28/simreport/prj/fulltextindex/internal/repository/document"
	"github.com/zuzuka28/simreport/prj/fulltextindex/internal/repository/filestorage"
	"github.com/zuzuka28/simreport/prj/fulltextindex/internal/repository/fulltextindex"
	document2 "github.com/zuzuka28/simreport/prj/fulltextindex/internal/service/document"
	fulltextindex2 "github.com/zuzuka28/simreport/prj/fulltextindex/internal/service/fulltextindex"
	"net"
	"net/http"
	"sync"
	"time"
)

// Injectors from wire.go:

func InitElastic(contextContext context.Context, configConfig *config.Config) (*elasticsearch.Client, error) {
	elasticutilConfig := configConfig.Elastic
	client, err := elasticutil.NewClientWithStartup(contextContext, elasticutilConfig)
	if err != nil {
		return nil, err
	}
	return client, nil
}

func InitFilestorageRepository(client *minio.Client, configConfig *config.Config, metricsMetrics *metrics.Metrics) (*filestorage.Repository, error) {
	repository := filestorage.NewRepository(client, metricsMetrics)
	return repository, nil
}

func InitDocumentRepository(conn *nats.Conn, metricsMetrics *metrics.Metrics) (*document.Repository, error) {
	repository := document.NewRepository(conn, metricsMetrics)
	return repository, nil
}

func InitDocumentService(repository *document.Repository) (*document2.Service, error) {
	service := document2.NewService(repository)
	return service, nil
}

func InitFulltextIndexRepository(client *elasticsearch.Client, configConfig *config.Config, metricsMetrics *metrics.Metrics) (*fulltextindex.Repository, error) {
	opts := configConfig.FulltextRepo
	repository, err := fulltextindex.NewRepository(opts, client, metricsMetrics)
	if err != nil {
		return nil, err
	}
	return repository, nil
}

func InitFulltextIndexService(repository *fulltextindex.Repository) (*fulltextindex2.Service, error) {
	service := fulltextindex2.NewService(repository)
	return service, nil
}

func InitFulltextHandler(service *fulltextindex2.Service, documentService *document2.Service, repository *filestorage.Repository) (*fulltextindex3.Handler, error) {
	handler := fulltextindex3.NewHandler(service, documentService, repository)
	return handler, nil
}

func InitIndexerHandler(service *fulltextindex2.Service, documentService *document2.Service, repository *filestorage.Repository) (*indexer.Handler, error) {
	handler := indexer.NewHandler(service, documentService, repository)
	return handler, nil
}

func InitNatsMicroAPI(contextContext context.Context, configConfig *config.Config, metricsMetrics *metrics.Metrics) (*server.Server, error) {
	conn, err := ProvideNats(contextContext, configConfig)
	if err != nil {
		return nil, err
	}
	client, err := InitElastic(contextContext, configConfig)
	if err != nil {
		return nil, err
	}
	repository, err := InitFulltextIndexRepository(client, configConfig, metricsMetrics)
	if err != nil {
		return nil, err
	}
	service, err := InitFulltextIndexService(repository)
	if err != nil {
		return nil, err
	}
	documentRepository, err := InitDocumentRepository(conn, metricsMetrics)
	if err != nil {
		return nil, err
	}
	documentService, err := InitDocumentService(documentRepository)
	if err != nil {
		return nil, err
	}
	minioClient, err := ProvideS3(contextContext, configConfig)
	if err != nil {
		return nil, err
	}
	filestorageRepository, err := InitFilestorageRepository(minioClient, configConfig, metricsMetrics)
	if err != nil {
		return nil, err
	}
	handler, err := InitFulltextHandler(service, documentService, filestorageRepository)
	if err != nil {
		return nil, err
	}
	serverServer := server.NewServer(conn, handler, metricsMetrics)
	return serverServer, nil
}

func InitNatsEventAPI(contextContext context.Context, configConfig *config.Config, metricsMetrics *metrics.Metrics) (*server2.Server, error) {
	conn, err := ProvideNats(contextContext, configConfig)
	if err != nil {
		return nil, err
	}
	client, err := InitElastic(contextContext, configConfig)
	if err != nil {
		return nil, err
	}
	repository, err := InitFulltextIndexRepository(client, configConfig, metricsMetrics)
	if err != nil {
		return nil, err
	}
	service, err := InitFulltextIndexService(repository)
	if err != nil {
		return nil, err
	}
	documentRepository, err := InitDocumentRepository(conn, metricsMetrics)
	if err != nil {
		return nil, err
	}
	documentService, err := InitDocumentService(documentRepository)
	if err != nil {
		return nil, err
	}
	minioClient, err := ProvideS3(contextContext, configConfig)
	if err != nil {
		return nil, err
	}
	filestorageRepository, err := InitFilestorageRepository(minioClient, configConfig, metricsMetrics)
	if err != nil {
		return nil, err
	}
	handler, err := InitIndexerHandler(service, documentService, filestorageRepository)
	if err != nil {
		return nil, err
	}
	serverServer := server2.NewServer(conn, handler)
	return serverServer, nil
}

// wire.go:

//nolint:gochecknoglobals
var (
	metricsS    *metrics.Metrics
	metricsOnce sync.Once
)

func ProvideMetrics() *metrics.Metrics {
	return metrics.New()
}

func ProvideConfig(path string) (*config.Config, error) {
	cfg, err := config.New(path)
	if err != nil {
		return nil, err
	}

	defaultTransportDialContext := func(
		dialer *net.Dialer,
	) func(context.Context, string, string) (net.Conn, error) {
		return dialer.DialContext
	}

	transport := &httpinstumentation.InstumentedTransport{
		Transport: &http.Transport{
			Proxy: http.ProxyFromEnvironment,
			DialContext: defaultTransportDialContext(&net.Dialer{
				Timeout:   30 * time.Second,
				KeepAlive: 30 * time.Second,
			}),
			ForceAttemptHTTP2:     true,
			MaxIdleConns:          100,
			IdleConnTimeout:       90 * time.Second,
			TLSHandshakeTimeout:   10 * time.Second,
			ExpectContinueTimeout: 1 * time.Second,
		},
		ExtractAttrs: func(ctx context.Context) []any {
			return []any{"request_id", ctx.Value(model.RequestIDKey)}
		},
		LogRequestBody:  true,
		LogResponseBody: false,
	}

	cfg.Elastic.Transport = transport
	cfg.S3.Transport = transport

	return cfg, nil
}

//nolint:gochecknoglobals
var (
	natsCli     *nats.Conn
	natsCliOnce sync.Once
)

func ProvideNats(
	_ context.Context,
	cfg *config.Config,
) (*nats.Conn, error) {
	var err error

	natsCliOnce.Do(func() {
		natsCli, err = nats.Connect(cfg.Nats)
	})

	return natsCli, err
}

//nolint:gochecknoglobals
var (
	s3Cli     *minio.Client
	s3CliOnce sync.Once
)

func ProvideS3(
	ctx context.Context,
	cfg *config.Config,
) (*minio.Client, error) {
	var err error

	s3CliOnce.Do(func() {
		s3Cli, err = minioutil.NewClientWithStartup(ctx, cfg.S3)
	})

	return s3Cli, err
}
