openapi: 3.0.0
info:
  title: Document Similarity API
  description: API для анализа сходства документов и поиска документов по имени
  version: 1.5.0

paths:
  /document/upload:
    post:
      summary: Загрузка документа
      description: Загружает документ для дальнейшего анализа на сходство.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/UploadRequest"
      responses:
        "200":
          $ref: "#/components/responses/UploadSuccess"
        "400":
          $ref: "#/components/responses/BadRequest"

  /document/{document_id}/download:
    get:
      summary: Скачать документ
      description: Позволяет скачать загруженный документ по его идентификатору.
      parameters:
        - $ref: "#/components/parameters/DocumentId"
      responses:
        "200":
          description: Успешная загрузка документа
          headers:
            Content-Disposition:
              schema:
                type: string
                example: attachment; filename="example.docx"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "404":
          $ref: "#/components/responses/DocumentNotFound"

components:
  schemas:
    UploadRequest:
      type: object
      properties:
        document:
          type: string
          format: binary
          description: Документ для загрузки

    Document:
      type: object
      properties:
        ID:
          type: string
        ImageIDs:
          type: array
          items:
            type: string
        TextContent:
          type: string
          description: Содержимое текста документа

  responses:
    UploadSuccess:
      description: Документ успешно загружен
      content:
        application/json:
          schema:
            type: object
            properties:
              documentID:
                type: string
                description: Уникальный идентификатор загруженного документа

    DocumentNotFound:
      description: Документ не найден
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Документ не найден"

    BadRequest:
      description: Ошибка валидации или неверный формат запроса
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Неверный запрос"

    ServerError:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Ошибка сервера"

  parameters:
    DocumentId:
      name: document_id
      in: path
      required: true
      schema:
        type: string
      description: Уникальный идентификатор документа
