// Code generated by protoc-gen-natsmicro. DO NOT EDIT.

package fulltextindex

import (
	"context"
	"fmt"
	"time"

	"github.com/nats-io/nats.go"
	"github.com/nats-io/nats.go/micro"
	"google.golang.org/protobuf/proto"
)

type Handler func(ctx context.Context, req micro.Request)

type Middleware func(Handler) Handler

// FullTextIndexServiceServer is the server API for FullTextIndexService service.
type FullTextIndexServiceServer interface {
	SearchSimilar(context.Context, *SearchSimilarRequest) (*SearchSimilarResponse, error)
}

type FullTextIndexServiceServerConfig struct {
	micro.Config
	RequestTimeout time.Duration
	Middleware     Middleware
	OnError        func(ctx context.Context, err error)
}

type FullTextIndexServiceNatsServer struct {
	srv  micro.Service
	impl FullTextIndexServiceServer
	cfg  FullTextIndexServiceServerConfig
}

// NewFullTextIndexServiceNatsServer  creates a new NATS microservice server.
func NewFullTextIndexServiceNatsServer(
	cfg FullTextIndexServiceServerConfig,
	nc *nats.Conn,
	impl FullTextIndexServiceServer,
) (*FullTextIndexServiceNatsServer, error) {
	srv, err := micro.AddService(nc, cfg.Config)
	if err != nil {
		return nil, fmt.Errorf("failed to create microservice: %w", err)
	}

	if cfg.RequestTimeout == 0 {
		cfg.RequestTimeout = time.Second * 60
	}

	s := &FullTextIndexServiceNatsServer{
		srv:  srv,
		impl: impl,
		cfg:  cfg,
	}

	group := srv.AddGroup(cfg.Name)

	// Register handlers
	if err := group.AddEndpoint("search_similar", s.toMicroHandler(s.handleSearchSimilar)); err != nil {
		return nil, fmt.Errorf("failed to add endpoint SearchSimilar: %w", err)
	}

	return s, nil
}

// Stop stops the microservice.
func (s *FullTextIndexServiceNatsServer) Stop() error {
	return s.srv.Stop()
}

func (s *FullTextIndexServiceNatsServer) toMicroHandler(h Handler) micro.HandlerFunc {
	return func(req micro.Request) {
		ctx, cancel := context.WithTimeout(context.Background(), s.cfg.RequestTimeout)
		defer cancel()

		if s.cfg.Middleware != nil {
			h = s.cfg.Middleware(h)
		}

		h(ctx, req)
	}
}

func (s *FullTextIndexServiceNatsServer) handleSearchSimilar(
	ctx context.Context,
	req micro.Request,
) {
	msg := new(SearchSimilarRequest)

	if err := proto.Unmarshal(req.Data(), msg); err != nil {
		req.Error("500", "unproccessable request", nil, nil)
		return
	}

	res, err := s.impl.SearchSimilar(ctx, msg)
	if err != nil {
		req.Error("500", "server error", nil, nil)
		return
	}

	resp, err := proto.Marshal(res)
	if err != nil {
		if s.cfg.OnError != nil {
			s.cfg.OnError(ctx, err)
		}

		req.Error("500", "server error", nil, nil)
		return
	}

	req.Respond(resp)
}

// FullTextIndexServiceClient is the client API for FullTextIndexService service.
type FullTextIndexServiceClient struct {
	nc *nats.Conn
}

// NewFullTextIndexServiceClient creates a new NATS microservice client.
func NewFullTextIndexServiceClient(nc *nats.Conn) *FullTextIndexServiceClient {
	return &FullTextIndexServiceClient{nc: nc}
}

func (c *FullTextIndexServiceClient) SearchSimilar(
	ctx context.Context,
	req *SearchSimilarRequest,
) (*SearchSimilarResponse, error) {
	resp := new(SearchSimilarResponse)

	data, err := proto.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	msg, err := c.nc.RequestWithContext(ctx, "fulltextindexservice.search_similar", data)
	if err != nil {
		return nil, fmt.Errorf("failed to send request: %w", err)
	}

	if err := proto.Unmarshal(msg.Data, resp); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return resp, nil
}
