/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Загрузка документа
         * @description Загружает документ для дальнейшего анализа на сходство.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": components["schemas"]["UploadRequest"];
                };
            };
            responses: {
                200: components["responses"]["UploadSuccess"];
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{document_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Скачать документ
         * @description Позволяет скачать загруженный документ по его идентификатору.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Уникальный идентификатор документа */
                    document_id: components["parameters"]["DocumentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Успешная загрузка документа */
                200: {
                    headers: {
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                404: components["responses"]["DocumentNotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UploadRequest: {
            /**
             * Format: binary
             * @description Документ для загрузки
             */
            document?: string;
        };
        Document: {
            ID?: string;
            ImageIDs?: string[];
            /** @description Содержимое текста документа */
            TextContent?: string;
        };
    };
    responses: {
        /** @description Документ успешно загружен */
        UploadSuccess: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Уникальный идентификатор загруженного документа */
                    documentID?: string;
                };
            };
        };
        /** @description Документ не найден */
        DocumentNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Документ не найден */
                    error?: string;
                };
            };
        };
        /** @description Ошибка валидации или неверный формат запроса */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Неверный запрос */
                    error?: string;
                };
            };
        };
        /** @description Внутренняя ошибка сервера */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example Ошибка сервера */
                    error?: string;
                };
            };
        };
    };
    parameters: {
        /** @description Уникальный идентификатор документа */
        DocumentId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
