metricsPort: 9090
nats: nats://localhost:4222
elastic:
  hosts:
    - http://localhost:9200/
  startupIndex:
    - index: "fulltext_index"
      updateMapping: true
      createMapping: true
      mappingPath: "config/mappings/fulltext_index.json"
      alias: ""
      shards: 1
      replics: 1
s3:
  endpoint: "localhost:9000"
  accessKeyID: "minio"
  secretAccessKey: "minio123"
  buckets:
    - texts
fulltextRepo:
  index: "fulltext_index"
