openapi: 3.0.0
info:
  title: Document Similarity API
  version: 0.0.1

paths:
  /{document_id}/download:
    get:
      summary: Download document
      description: Allows downloading an uploaded document by its identifier.
      parameters:
        - $ref: "#/components/parameters/DocumentId"
      responses:
        "200":
          description: Document downloaded successfully
          headers:
            Content-Disposition:
              schema:
                type: string
                example: attachment; filename="example.docx"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "404":
          $ref: "#/components/responses/DocumentNotFound"

  /document/upload:
    post:
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/UploadRequest"
      responses:
        "200":
          $ref: "#/components/responses/UploadSuccess"
        "400":
          $ref: "#/components/responses/BadRequest"

  /attribute:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttributeRequest"
      responses:
        "200":
          $ref: "#/components/responses/AttributeResult"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/ServerError"

  /document/search:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchRequest"
      responses:
        "200":
          $ref: "#/components/responses/SearchResult"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/ServerError"

  /analyze/{document_id}/similar:
    get:
      parameters:
        - $ref: "#/components/parameters/DocumentId"
      responses:
        "200":
          $ref: "#/components/responses/SimilaritySearchResult"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/ServerError"

  /analyze/history:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SimilaritySearchHistoryRequest"
      responses:
        "200":
          $ref: "#/components/responses/SimilaritySearchHistoryResult"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/ServerError"

components:
  schemas:
    UploadRequest:
      type: object
      properties:
        document:
          type: string
          format: binary
          description: Document to upload
        groupID:
          type: array
          items:
            type: string
        parentID:
          type: string
        version:
          type: integer
      required:
        - document

    AttributeRequest:
      type: object
      properties:
        attribute:
          type: string
      required:
        - attribute

    SearchRequest:
      type: object
      properties:
        parentID:
          type: string
        name:
          type: string
        version:
          type: string
        groupID:
          type: array
          items:
            type: string

    Document:
      type: object
      properties:
        ID:
          type: string
        ImageIDs:
          type: array
          items:
            type: string
        TextContent:
          type: string

    DocumentSummary:
      type: object
      properties:
        groupID:
          type: array
          items:
            type: string
        parentID:
          type: string
        version:
          type: integer
        id:
          type: string
        name:
          type: string
        lastUpdated:
          type: string
          format: date-time

    AnalyzedDocumentMatch:
      type: object
      properties:
        id:
          type: string
        rate:
          type: number
          format: float
        highlights:
          type: array
          items:
            type: string
        similarImages:
          type: array
          items:
            type: string

    SimilaritySearchHistoryRequest:
      type: object
      properties:
        documentID:
          type: string
        limit:
          type: integer
        offset:
          type: integer
        dateFrom:
          type: string
          format: date-time
        dateTo:
          type: string
          format: date-time

    SimilaritySearchHistory:
      type: object
      properties:
        date:
          type: string
          format: date-time
        documentID:
          type: string
        id:
          type: string
        matches:
          type: array
          items:
            $ref: "#/components/schemas/AnalyzedDocumentMatch"

    Attribute:
      type: object
      properties:
        label:
          type: string
        value:
          type: string
      required:
        - label
        - value

  responses:
    UploadSuccess:
      content:
        application/json:
          schema:
            type: object
            properties:
              documentID:
                type: string

    AttributeResult:
      content:
        application/json:
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: "#/components/schemas/Attribute"

    SearchResult:
      content:
        application/json:
          schema:
            type: object
            properties:
              documents:
                type: array
                items:
                  $ref: "#/components/schemas/DocumentSummary"

    SimilaritySearchResult:
      content:
        application/json:
          schema:
            type: object
            properties:
              documents:
                type: array
                items:
                  $ref: "#/components/schemas/AnalyzedDocumentMatch"

    SimilaritySearchHistoryResult:
      content:
        application/json:
          schema:
            type: object
            properties:
              documents:
                type: array
                items:
                  $ref: "#/components/schemas/SimilaritySearchHistory"
              count:
                type: integer

    DocumentNotFound:
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string

    BadRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string

    ServerError:
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string

  parameters:
    DocumentId:
      name: document_id
      in: path
      required: true
      schema:
        type: string
