global:
  env: dev # change to use another config

replicaCount: 1

image:
  repository: zuzuka28/document
  pullPolicy: IfNotPresent
  tag: "2025-01-13_15-27_30f3538c18ff389d99726d0c632567c85eb315df"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

nodeSelector: {}

tolerations: []

affinity: {}

config:
  dev: |
    # check config example in prj/document
