metricsPort: 9090
nats: nats://localhost:4222
bot:
  token:
elastic:
  hosts:
    - http://localhost:9200/
  startupIndex:
    - index: "user_state"
      updateMapping: true
      createMapping: true
      mappingPath: "config/mappings/user_state.json"
      alias: ""
      shards: 1
      replics: 1
userStateRepo:
  index: "user_state"
