import createFetchClient from 'openapi-fetch';
import createClient from 'openapi-react-query';

import type { paths } from './schema'; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: process.env.BACKEND_API_URL,
});

const api = createClient(fetchClient);

export default api;
