replicaCount: 1

image:
  repository: zuzuka28/anysave
  pullPolicy: IfNotPresent
  tag: "2025-01-12_16-22_d251d7014fa1d1d700a5dbcd97edf4bccc13d3d9"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

service:
  type: ClusterIP
  port: 80
  domain: local

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
