port: 8000
s3:
  endpoint: "localhost:9000"
  accessKeyID: "minio"
  secletAccessKey: "minio123"
  buckets:
    - images
    - texts
    - anysave
nats: nats://localhost:4222
tika: http://localhost:9998
elastic:
  hosts:
    - http://localhost:9200/
  indexopts:
    - index: "document"
      updateMapping: true
      createMapping: true
      mappingPath: "config/mappings/document.json"
      alias: ""
      shards: 1
      replics: 1
    - index: "analyze_history"
      updateMapping: true
      createMapping: true
      mappingPath: "config/mappings/analyze_history.json"
      alias: ""
      shards: 1
      replics: 1
attributeRepo:
  index: "document"
documentRepo:
  index: "document"
analyzeHistoryRepo:
  index: "analyze_history"
