// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// BodyHashImageHashImagePost defines model for Body_hash_image_hash_image_post.
type BodyHashImageHashImagePost struct {
	File openapi_types.File `json:"file"`
}

// BodyVectorizeImageVectorizeImagePost defines model for Body_vectorize_image_vectorize_image_post.
type BodyVectorizeImageVectorizeImagePost struct {
	File openapi_types.File `json:"file"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// ImageHashesResponse defines model for ImageHashesResponse.
type ImageHashesResponse struct {
	Ahash       string    `json:"ahash"`
	AhashVector []float32 `json:"ahash_vector"`
	Dhash       string    `json:"dhash"`
	DhashVector []float32 `json:"dhash_vector"`
	Phash       string    `json:"phash"`
	PhashVector []float32 `json:"phash_vector"`
	Whash       string    `json:"whash"`
	WhashVector []float32 `json:"whash_vector"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Loc  []ValidationError_Loc_Item `json:"loc"`
	Msg  string                     `json:"msg"`
	Type string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// VectorizeImageReponse defines model for VectorizeImageReponse.
type VectorizeImageReponse struct {
	Vector []float32 `json:"vector"`
}

// VectorizeTextReponse defines model for VectorizeTextReponse.
type VectorizeTextReponse struct {
	Vector []float32 `json:"vector"`
}

// VectorizeTextRequest defines model for VectorizeTextRequest.
type VectorizeTextRequest struct {
	Text string `json:"text"`
}

// HashImageHashImagePostMultipartRequestBody defines body for HashImageHashImagePost for multipart/form-data ContentType.
type HashImageHashImagePostMultipartRequestBody = BodyHashImageHashImagePost

// VectorizeImageVectorizeImagePostMultipartRequestBody defines body for VectorizeImageVectorizeImagePost for multipart/form-data ContentType.
type VectorizeImageVectorizeImagePostMultipartRequestBody = BodyVectorizeImageVectorizeImagePost

// VectorizeTextVectorizeTextPostJSONRequestBody defines body for VectorizeTextVectorizeTextPost for application/json ContentType.
type VectorizeTextVectorizeTextPostJSONRequestBody = VectorizeTextRequest

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// HashImageHashImagePostWithBody request with any body
	HashImageHashImagePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// VectorizeImageVectorizeImagePostWithBody request with any body
	VectorizeImageVectorizeImagePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// VectorizeTextVectorizeTextPostWithBody request with any body
	VectorizeTextVectorizeTextPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	VectorizeTextVectorizeTextPost(ctx context.Context, body VectorizeTextVectorizeTextPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) HashImageHashImagePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHashImageHashImagePostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VectorizeImageVectorizeImagePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVectorizeImageVectorizeImagePostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VectorizeTextVectorizeTextPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVectorizeTextVectorizeTextPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VectorizeTextVectorizeTextPost(ctx context.Context, body VectorizeTextVectorizeTextPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVectorizeTextVectorizeTextPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewHashImageHashImagePostRequestWithBody generates requests for HashImageHashImagePost with any type of body
func NewHashImageHashImagePostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/hash/image")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewVectorizeImageVectorizeImagePostRequestWithBody generates requests for VectorizeImageVectorizeImagePost with any type of body
func NewVectorizeImageVectorizeImagePostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/vectorize/image")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewVectorizeTextVectorizeTextPostRequest calls the generic VectorizeTextVectorizeTextPost builder with application/json body
func NewVectorizeTextVectorizeTextPostRequest(server string, body VectorizeTextVectorizeTextPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewVectorizeTextVectorizeTextPostRequestWithBody(server, "application/json", bodyReader)
}

// NewVectorizeTextVectorizeTextPostRequestWithBody generates requests for VectorizeTextVectorizeTextPost with any type of body
func NewVectorizeTextVectorizeTextPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/vectorize/text")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// HashImageHashImagePostWithBodyWithResponse request with any body
	HashImageHashImagePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HashImageHashImagePostResponse, error)

	// VectorizeImageVectorizeImagePostWithBodyWithResponse request with any body
	VectorizeImageVectorizeImagePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VectorizeImageVectorizeImagePostResponse, error)

	// VectorizeTextVectorizeTextPostWithBodyWithResponse request with any body
	VectorizeTextVectorizeTextPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VectorizeTextVectorizeTextPostResponse, error)

	VectorizeTextVectorizeTextPostWithResponse(ctx context.Context, body VectorizeTextVectorizeTextPostJSONRequestBody, reqEditors ...RequestEditorFn) (*VectorizeTextVectorizeTextPostResponse, error)
}

type HashImageHashImagePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ImageHashesResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r HashImageHashImagePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HashImageHashImagePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VectorizeImageVectorizeImagePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VectorizeImageReponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r VectorizeImageVectorizeImagePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VectorizeImageVectorizeImagePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VectorizeTextVectorizeTextPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VectorizeTextReponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r VectorizeTextVectorizeTextPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VectorizeTextVectorizeTextPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// HashImageHashImagePostWithBodyWithResponse request with arbitrary body returning *HashImageHashImagePostResponse
func (c *ClientWithResponses) HashImageHashImagePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HashImageHashImagePostResponse, error) {
	rsp, err := c.HashImageHashImagePostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHashImageHashImagePostResponse(rsp)
}

// VectorizeImageVectorizeImagePostWithBodyWithResponse request with arbitrary body returning *VectorizeImageVectorizeImagePostResponse
func (c *ClientWithResponses) VectorizeImageVectorizeImagePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VectorizeImageVectorizeImagePostResponse, error) {
	rsp, err := c.VectorizeImageVectorizeImagePostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVectorizeImageVectorizeImagePostResponse(rsp)
}

// VectorizeTextVectorizeTextPostWithBodyWithResponse request with arbitrary body returning *VectorizeTextVectorizeTextPostResponse
func (c *ClientWithResponses) VectorizeTextVectorizeTextPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*VectorizeTextVectorizeTextPostResponse, error) {
	rsp, err := c.VectorizeTextVectorizeTextPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVectorizeTextVectorizeTextPostResponse(rsp)
}

func (c *ClientWithResponses) VectorizeTextVectorizeTextPostWithResponse(ctx context.Context, body VectorizeTextVectorizeTextPostJSONRequestBody, reqEditors ...RequestEditorFn) (*VectorizeTextVectorizeTextPostResponse, error) {
	rsp, err := c.VectorizeTextVectorizeTextPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVectorizeTextVectorizeTextPostResponse(rsp)
}

// ParseHashImageHashImagePostResponse parses an HTTP response from a HashImageHashImagePostWithResponse call
func ParseHashImageHashImagePostResponse(rsp *http.Response) (*HashImageHashImagePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HashImageHashImagePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ImageHashesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseVectorizeImageVectorizeImagePostResponse parses an HTTP response from a VectorizeImageVectorizeImagePostWithResponse call
func ParseVectorizeImageVectorizeImagePostResponse(rsp *http.Response) (*VectorizeImageVectorizeImagePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VectorizeImageVectorizeImagePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VectorizeImageReponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseVectorizeTextVectorizeTextPostResponse parses an HTTP response from a VectorizeTextVectorizeTextPostWithResponse call
func ParseVectorizeTextVectorizeTextPostResponse(rsp *http.Response) (*VectorizeTextVectorizeTextPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VectorizeTextVectorizeTextPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VectorizeTextReponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
