version: "3.7"

services:
  allinone_backend:
    build:
      context: ../../prj/allinone
      dockerfile: build/docker/Dockerfile
    image: zuzuka28/simrep_allinone:latest
    command: ["--config", "/config/config.yaml"]
    configs:
      - source: allinone_backend-config
        target: /config/config.yaml
    volumes:
      - ../../prj/document/config/mappings:/mappings

  vectorizer:
    build:
      context: ../../prj/vectorizer
      dockerfile: build/docker/Dockerfile
    image: zuzuka28/simrep_vectorizer:latest
    command: ["python", "-m", "src.api.run"]
    configs:
      - source: vectorizer-config
        target: /config/config.yaml

  tgbot:
    build:
      context: ../../prj/tgbot
      dockerfile: build/docker/Dockerfile
    image: zuzuka28/simrep_tgbot:latest
    command: ["--config", "/config/config.yaml"]
    configs:
      - source: tgbot-config
        target: /config/config.yaml
    volumes:
      - ../../prj/tgbot/config/mappings:/mappings

  minio:
    image: minio/minio
    volumes:
      - minio_vol:/data
    command: server --console-address ":9001" /data
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}

  elasticsearch:
    image: elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - elastic_vol:/usr/share/elasticsearch/data

  nats1:
    image: docker.io/nats
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats1_vol:/data
    command:
      - "--name=nats1"
      - "--cluster_name=c1"
      - "--cluster=nats://nats1:6222"
      - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"

  nats2:
    image: docker.io/nats
    ports:
      - "4223:4222"
      - "8223:8222"
    volumes:
      - nats2_vol:/data
    command:
      - "--name=nats2"
      - "--cluster_name=c1"
      - "--cluster=nats://nats2:6222"
      - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"

  nats3:
    image: docker.io/nats
    ports:
      - "4224:4222"
      - "8224:8222"
    volumes:
      - nats3_vol:/data
    command:
      - "--name=nats3"
      - "--cluster_name=c1"
      - "--cluster=nats://nats3:6222"
      - "--routes=nats-route://nats1:6222,nats-route://nats2:6222,nats-route://nats3:6222"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"

  tika:
    image: zuzuka28/simrep_tika
    build:
      context: ../../thirdparty/tika
      dockerfile: build/Dockerfile
      args:
        - TIKA_VERSION=3.0.0

configs:
  allinone_backend-config:
    file: ./configs/allinone_backend.yaml
  vectorizer-config:
    file: ./configs/vectorizer.yaml
  tgbot-config:
    file: ./configs/tgbot.yaml

volumes:
  elastic_vol:
  minio_vol:
  nats1_vol:
  nats2_vol:
  nats3_vol:
