port: 8000
s3:
  endpoint: "localhost:9000"
  accessKeyID: "minio"
  secletAccessKey: "minio123"
  buckets:
    - document
    - image
nats: nats://localhost:4222
tika: http://localhost:9998
elastic:
  hosts:
    - http://localhost:9200/
  indexopts:
    - index: "document"
      updateMapping: true
      createMapping: true
      mappingPath: "config/mappings/document.json"
      alias: ""
      shards: 1
      replics: 1
    - index: "analyzed_document"
      updateMapping: true
      createMapping: true
      mappingPath: "config/mappings/document_analysis.json"
      alias: ""
      shards: 1
      replics: 1
documentRepo:
  index: "document"
analyzedDocumentRepo:
  index: "analyzed_document"
vectorizerService: "http://localhost:8081"
