port: 8000
s3:
  endpoint: "localhost:9000"
  accessKeyID: "minio"
  secletAccessKey: "minio123"
  buckets:
    - document
    - image
elastic:
  hosts:
    - http://localhost:9200/
  indexopts:
    - index: "document"
      updateMapping: true
      createMapping: true
      mappingPath: "config/mappings/document.json"
      alias: ""
      shards: 1
      replics: 1
    - index: "analyzed_document"
      updateMapping: true
      createMapping: true
      mappingPath: "config/mappings/document_analysis.json"
      alias: ""
      shards: 1
      replics: 1
imageRepo:
  bucket: "image"
documentFileRepo:
  bucket: "document"
documentRepo:
  index: "document"
analyzedDocumentRepo:
  index: "analyzed_document"
vectorizerService: "http://localhost:8081"
notifyProducer:
  dsn: "amqp://localhost:5672/"
  exchangeName: "notification"
  queueName: "notification"
  routingKey: ""
  maxRetries: 5
notifyConsumer:
  dsn: "amqp://localhost:5672/"
  queueName: "notification"
  maxRetries: 5
